"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import Image from "next/image";
import { useRouter, usePathname } from "next/navigation";
import {
  Search,
  User,
  Menu,
  X,
  ArrowRight,
  ChevronDown,
  ChevronUp
} from "lucide-react";
import { getCart } from "@/lib/cart";
import { useCurrency, CONTINENTS } from "@/providers/CurrencyProvider";
import { useSettings } from "@/providers/SettingsProvider";
import { HELP_LINKS } from "@/lib/helpLinks";

interface Category {
  id: string;
  name: string;
  slug: string;
  image?: string | null;
  children?: Category[];
}

interface HeaderProps {
  categories?: Category[];
}

// ─── About mega menu ──────────────────────────────────────────────────────────
// A different shape from the shop menus: one narrow column of text links on the
// left, then a row of large portrait image tiles with the label set over the
// image. Tiles are driven by `MenuItem.imageUrl`, so which entries get a tile —
// and which picture they use — stays editable from Admin → Menus.
function AboutMenuContent({ category, storeName }: { category: any; storeName: string }) {
  const items: any[] = category.children || [];

  // The bold heading doubles as the link to the main About page, mirroring the
  // reference. When such an entry exists it is lifted out of the list below so
  // the same destination isn't offered twice.
  const aboutIndex = items.findIndex(
    (i) => /^about/i.test(i.title || i.name || "") || (i.url || "") === "/pages/about-us"
  );
  const aboutEntry = aboutIndex >= 0 ? items[aboutIndex] : null;
  const links = aboutIndex >= 0 ? items.filter((_, idx) => idx !== aboutIndex) : items;

  const tiles = items.filter((i) => i.imageUrl);

  // Root title is usually just "About", so the brand name is appended — "About
  // drm Fashion". A title that already says more than that is left alone.
  const rootTitle = category.title || category.name || "About";
  const heading =
    /^about$/i.test(rootTitle.trim()) && storeName && storeName !== "My Store"
      ? `About ${storeName}`
      : rootTitle;

  const headingClass = "text-[17px] font-extrabold tracking-tight text-foreground";

  return (
    <div className="max-w-[1600px] mx-auto px-4 xl:px-8 py-8 flex flex-col lg:flex-row gap-8 xl:gap-12 w-full">
      {/* Left: heading + text links */}
      <div className="w-full lg:w-[230px] xl:w-[270px] shrink-0">
        {aboutEntry ? (
          <Link href={aboutEntry.url || "/pages/about-us"} className={`${headingClass} block w-fit hover:text-brand-700 transition-colors`}>
            {heading}
          </Link>
        ) : (
          <p className={headingClass}>{heading}</p>
        )}

        <ul className="mt-6 flex flex-col gap-4">
          {links.map((item) => (
            <li key={item.id}>
              <Link
                href={item.url || "#"}
                className="relative inline-block text-[15px] font-medium text-soft hover:text-brand-700 transition-colors after:absolute after:bottom-0 after:left-0 after:h-px after:w-0 after:bg-brand-500 after:transition-[width] after:duration-300 after:ease-out hover:after:w-full"
              >
                {item.title || item.name}
              </Link>
            </li>
          ))}
        </ul>
      </div>

      {/* Right: image tiles. Column count is inline rather than a Tailwind class
          because it depends on runtime data — an interpolated `grid-cols-${n}`
          would never be generated by Tailwind's static scan. */}
      {tiles.length > 0 && (
        <div
          className="grid flex-1 gap-3 xl:gap-4"
          style={{ gridTemplateColumns: `repeat(${tiles.length}, minmax(0, 1fr))` }}
        >
          {tiles.map((tile) => (
            <Link
              key={tile.id}
              href={tile.url || "#"}
              className="group/tile relative block aspect-[3/4] overflow-hidden rounded-2xl bg-brand-50"
            >
              <Image
                src={tile.imageUrl}
                alt={tile.title || tile.name || ""}
                fill
                sizes="(max-width: 1024px) 50vw, 30vw"
                className="object-cover transition-transform duration-700 ease-out group-hover/tile:scale-105"
              />
              <div className="absolute inset-0 bg-black/10 transition-colors group-hover/tile:bg-black/25" />
              <span className="absolute inset-0 flex items-center justify-center px-4 text-center text-xl xl:text-2xl font-extrabold tracking-tight text-white drop-shadow-[0_2px_8px_rgba(0,0,0,0.45)]">
                {tile.title || tile.name}
              </span>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}

function MegaMenuContent({ category }: { category: any }) {
  const { storeName } = useSettings();

  // Only use database-driven columns (children of the main category)
  const columns = category.children || [];

  const titleLower = (category.title || category.name || "").toLowerCase();
  const urlLower = (category.url || "").toLowerCase();

  // The About tree is a flat list of editorial pages, not a category hierarchy,
  // so it gets the tile layout instead of the four-column shop grid.
  if (titleLower === "about" || titleLower.startsWith("about ")) {
    return <AboutMenuContent category={category} storeName={storeName} />;
  }

  const isShopMenu =
    category.slug === 'man' || 
    category.slug === 'woman' || 
    category.slug === 'mens' || 
    category.slug === 'womens' ||
    titleLower === 'man' ||
    titleLower === 'woman' ||
    titleLower === 'men' ||
    titleLower === 'women' ||
    urlLower === '/category/man' ||
    urlLower === '/category/woman' ||
    urlLower.includes('category=man') ||
    urlLower.includes('category=woman');

  const hasImage = !!(category.imageUrl || category.image || isShopMenu);

  const imageUrl = category.imageUrl || category.image || (category.slug === 'women' || titleLower === 'woman' || titleLower === 'women' || urlLower.includes('woman') || urlLower.includes('women')
    ? "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800" 
    : "https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&q=80&w=800");

  // Group the columns into 4 vertical columns as requested
  const groupedColumns: any[][] = [[], [], [], []];
  
  if (isShopMenu) {
    columns.forEach((col: any) => {
      const name = (col.title || col.name || "").toLowerCase();
      if (name.includes("featured") || name.includes("sale")) {
        groupedColumns[0].push(col);
      } else if (name.includes("top") || name.includes("dress") || name.includes("accessory") || name.includes("accessories")) {
        groupedColumns[1].push(col);
      } else if (name.includes("bottom") || name.includes("footwear") || name.includes("shoe") || name.includes("specialty")) {
        groupedColumns[2].push(col);
      } else {
        groupedColumns[3].push(col);
      }
    });
  } else {
    // Just distribute sequentially starting from the left (Column 1)
    columns.forEach((col: any, idx: number) => {
      groupedColumns[idx % 4].push(col);
    });
  }

  return (
    <div className="max-w-[1600px] mx-auto px-4 xl:px-8 py-6 flex justify-between gap-6 xl:gap-8 w-full overflow-hidden">
      {/* Left Link Columns Container */}
      <div className="grid grid-cols-4 gap-y-8 gap-x-6 xl:gap-x-12 flex-1">
        {groupedColumns.map((colGroup, groupIdx) => (
          <div key={groupIdx} className="flex flex-col gap-6">
            {colGroup.map((col: any) => (
              <div key={col.id} className="flex flex-col gap-2">
                <Link href={col.url || (col.slug === '#' ? '#' : `/category/${col.slug}`)} className="relative font-bold text-foreground text-[15px] capitalize block w-fit after:absolute after:bottom-0 after:left-0 after:h-px after:w-0 after:bg-brand-500 after:transition-[width] after:duration-300 after:ease-out hover:after:w-full">
                  {col.title || col.name}
                </Link>
                {col.children && col.children.length > 0 && (
                  <ul className="space-y-2.5 text-soft text-[14px]">
                    {col.children.map((child: any) => {
                      // Check if it's a dynamic link (contains ? or starts with 'shop' or 'pages')
                      const slug = child.slug || child.url || '';
                      const isDynamic = slug.includes('?') || slug.startsWith('shop') || slug.startsWith('pages');
                      const href = child.url || (isDynamic ? `/${slug}` : `/category/${slug}`);
                      return (
                        <li key={child.id}>
                          <Link href={href} className="relative inline-block hover:text-brand-700 transition-colors after:absolute after:bottom-0 after:left-0 after:h-px after:w-0 after:bg-brand-500 after:transition-[width] after:duration-300 after:ease-out hover:after:w-full">
                            {child.title || child.name}
                          </Link>
                        </li>
                      );
                    })}
                  </ul>
                )}
              </div>
            ))}
          </div>
        ))}
      </div>

      {/* Right Image Container */}
      {hasImage && (
        <div className="w-[220px] xl:w-[260px] shrink-0">
          <Link href={category.url || `/category/${category.slug}`} className="block relative w-full aspect-[4/5] group/image overflow-hidden rounded-2xl bg-brand-50">
            <Image 
              src={imageUrl} 
              alt={category.title || category.name || "Category"} 
              fill
              className="object-cover group-hover/image:scale-105 transition-transform duration-700 ease-out" 
            />
            <div className="absolute inset-0 flex items-center justify-center bg-black/20">
              <span className="text-white text-lg xl:text-xl font-extrabold tracking-wide drop-shadow-lg text-center px-4">
                Shop {category.title || category.name}
              </span>
            </div>
          </Link>
        </div>
      )}
    </div>
  );
}

export default function HeaderClient({ menus }: { menus?: any[] }) {
  const router = useRouter();
  const pathname = usePathname();
  const { storeName, settings } = useSettings();
  const [categories, setCategories] = useState<any[]>(menus || []);
  const [cartItemsCount, setCartItemsCount] = useState(0);
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isSearchOpen, setIsSearchOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  
  // Brand Settings. Read straight off the settings context — the root layout
  // already loaded these on the server. This used to be state filled by a
  // `/api/settings` fetch on mount, which made it the third request for that
  // same endpoint on every page load, for one string.
  // `liveSlogan` only holds a value after an admin save (see the listener below).
  const [liveSlogan, setLiveSlogan] = useState<string | null>(null);
  const brandSlogan =
    liveSlogan ?? settings["brand_slogan"] ?? "Free shipping over ৳5,000 · 30-day easy returns";

  // Drives the header shadow once the page leaves the top
  const [isScrolled, setIsScrolled] = useState(false);

  const { 
    currencies, 
    selectedCurrency, 
    setCurrency, 
    selectedCountry, 
    setCountryAndCurrency 
  } = useCurrency();

  const selectedCountryInfo = CONTINENTS.flatMap((g) => g.countries).find(
    (c) => c.name === selectedCountry
  );
  const selectedCountryCode = selectedCountryInfo?.code || "";

  // Currency modal states
  const [isCurrencyModalOpen, setIsCurrencyModalOpen] = useState(false);
  const [isModalAnimating, setIsModalAnimating] = useState(false);
  const [countrySearchQuery, setCountrySearchQuery] = useState("");
  const [expandedContinents, setExpandedContinents] = useState<Record<string, boolean>>({ ASIA: true }); // Default ASIA open since Bangladesh is there

  // Mobile accordion expansion states
  const [expandedMobileCategories, setExpandedMobileCategories] = useState<Record<string, boolean>>({});
  const [expandedMobileSubCategories, setExpandedMobileSubCategories] = useState<Record<string, boolean>>({});

  const toggleMobileCategory = (id: string) => {
    setExpandedMobileCategories(prev => ({
      ...prev,
      [id]: !prev[id]
    }));
  };

  const toggleMobileSubCategory = (id: string) => {
    setExpandedMobileSubCategories(prev => ({
      ...prev,
      [id]: !prev[id]
    }));
  };

  const openCurrencyModal = () => {
    setIsCurrencyModalOpen(true);
    setCountrySearchQuery("");
    requestAnimationFrame(() => {
      setIsModalAnimating(true);
    });
  };

  const closeCurrencyModal = () => {
    setIsModalAnimating(false);
    setTimeout(() => {
      setIsCurrencyModalOpen(false);
    }, 500); // match duration-500
  };

  const toggleContinent = (name: string) => {
    setExpandedContinents(prev => ({
      ...prev,
      [name]: !prev[name]
    }));
  };

  const handleCountrySelect = (countryName: string, currencyCode: string) => {
    setCountryAndCurrency(countryName, currencyCode);
    closeCurrencyModal();
  };

  const searchResults = CONTINENTS.flatMap((g) => g.countries)
    .filter((c) => c.name.toLowerCase().includes(countrySearchQuery.toLowerCase()));

  // Fetch menus if not passed as prop
  useEffect(() => {
    if (menus && menus.length > 0) {
      setCategories(menus);
      return;
    }

    const fetchMenus = async () => {
      try {
        const res = await fetch("/api/menus");
        if (res.ok) {
          const data = await res.json();
          setCategories(data);
        }
      } catch (err) {
        console.error("Failed to fetch header menus:", err);
      }
    };
    fetchMenus();
  }, [menus]);

  // Real-time update when saving from admin. No fetch on mount any more — the
  // slogan is already in the settings context; this only runs when the admin
  // settings screen announces a save.
  useEffect(() => {
    const handleUpdate = async () => {
      try {
        const res = await fetch("/api/settings");
        if (res.ok) {
          const data = await res.json();
          if (data.brand_slogan) setLiveSlogan(data.brand_slogan);
        }
      } catch (err) {
        console.error("Failed to refresh brand settings:", err);
      }
    };
    window.addEventListener("brand-settings-updated", handleUpdate);
    return () => window.removeEventListener("brand-settings-updated", handleUpdate);
  }, []);

  // Shrink header/logo once the page is scrolled
  useEffect(() => {
    const handleScroll = () => setIsScrolled(window.scrollY > 20);
    handleScroll();
    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  // Sync cart count
  useEffect(() => {
    const updateCartCount = () => {
      const cart = getCart();
      const count = cart.reduce((sum, item) => sum + item.quantity, 0);
      setCartItemsCount(count);
    };

    updateCartCount();
    window.addEventListener("cart-updated", updateCartCount);
    window.addEventListener("storage", updateCartCount);

    return () => {
      window.removeEventListener("cart-updated", updateCartCount);
      window.removeEventListener("storage", updateCartCount);
    };
  }, []);

  // Close menus on page transition
  useEffect(() => {
    setIsMenuOpen(false);
    setIsSearchOpen(false);
  }, [pathname]);

  // Full-screen search overlay: Escape to close, lock body scroll while open
  useEffect(() => {
    if (!isSearchOpen) return;
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setIsSearchOpen(false);
    };
    window.addEventListener("keydown", handleKey);
    document.body.style.overflow = "hidden";
    return () => {
      window.removeEventListener("keydown", handleKey);
      document.body.style.overflow = "";
    };
  }, [isSearchOpen]);

  const handleSearchSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (searchQuery.trim()) {
      router.push(`/shop?query=${encodeURIComponent(searchQuery.trim())}`);
      setIsSearchOpen(false);
      setSearchQuery("");
    }
  };

  return (
    <>
      {/* 1. ANNOUNCEMENT BAR — the copper→cyan gradient band that opens every
          page. Slogan centred, utilities on the right; both drop out on mobile
          so the sale message keeps the width to itself. */}
      <div className="w-full bg-gradient-to-r from-brand-700 via-brand-500 to-aqua-600 text-white py-2.5 px-4 text-[12px] font-semibold z-60 relative flex justify-between items-center">
        <div className="hidden md:flex flex-1"></div>
        <div className="flex-1 text-center whitespace-nowrap">
          {brandSlogan}
        </div>
        <div className="hidden md:flex flex-1 justify-end items-center gap-5 text-[11.5px]">
          <button
            onClick={openCurrencyModal}
            className="hover:text-white/75 transition-colors flex items-center gap-2 cursor-pointer"
          >
            {selectedCountryCode && (
              <img
                src={`https://flagcdn.com/w40/${selectedCountryCode.toLowerCase()}.png`}
                alt=""
                className="w-4.5 h-3 object-cover rounded-lg shrink-0 border border-white/30"
              />
            )}
            <span>{selectedCurrency?.symbol} {selectedCurrency?.code}</span>
          </button>
          {/* Help dropdown */}
          <div className="relative group/help">
            <Link
              href="/pages/help-center"
              className="hover:text-white/75 transition-colors flex items-center gap-1 py-1"
            >
              Help
            </Link>

            <div className="absolute right-0 top-full pt-3 opacity-0 invisible translate-y-1 group-hover/help:opacity-100 group-hover/help:visible group-hover/help:translate-y-0 focus-within:opacity-100 focus-within:visible focus-within:translate-y-0 transition-all duration-200 z-[110]">
              <ul className="min-w-[240px] sg-card sg-raise overflow-hidden py-2 text-left">
                {HELP_LINKS.map((item) => (
                  <li key={item.href}>
                    <Link
                      href={item.href}
                      className="block px-6 py-2.5 text-[14px] font-medium text-soft hover:bg-brand-50 hover:text-brand-700 transition-colors whitespace-nowrap"
                    >
                      {item.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </div>

      {/* 2. NAVIGATION HEADER — logo left, a white pill holding the nav in the
          middle, round icon buttons right. Blurred cream rather than solid so
          content scrolling under it stays faintly visible. */}
      <header
        className={`sticky top-0 z-50 w-full bg-cream/92 backdrop-blur-xl transition-shadow duration-300 border-b border-line ${
          isScrolled ? "shadow-sg" : ""
        }`}
      >
        <div className="max-w-[1600px] mx-auto px-5 lg:px-8 flex items-center gap-4 xl:gap-7 min-h-[74px]">

          {/* Menu Icon (Mobile) */}
          <button
            onClick={() => setIsMenuOpen(true)}
            className="lg:hidden sg-icon cursor-pointer text-foreground"
            aria-label="Open Menu"
          >
            <Menu className="w-5 h-5" />
          </button>

          {/* Logo */}
          <Link href="/" className="hover:opacity-90 transition-opacity shrink-0">
            <div className="relative h-11 w-[132px]">
              <Image src={settings["brand_logo_url"] || "/logo.svg"} alt={storeName} fill className="object-contain object-left" />
            </div>
          </Link>

          {/* Nav pill — the design's signature move. Sits in its own white
              capsule so the cream bar reads as page, not chrome. */}
          <nav className="hidden lg:flex items-center gap-1 mx-auto sg-card rounded-full p-1.5">
            {categories.map((cat) => (
              <div key={cat.id} className="group/cat">
                <Link
                  href={cat.url || `/category/${cat.slug}`}
                  className="block rounded-full px-4 xl:px-5 py-2.5 text-[14px] font-semibold text-soft hover:text-brand-700 hover:bg-brand-50 transition-colors whitespace-nowrap"
                >
                  {cat.title || cat.name}
                </Link>

                {/* Mega menu. Detached from the pill and pinned to the header, so
                    it spans the full width no matter which item opened it. */}
                {cat.children && cat.children.length > 0 && (
                  <div className="absolute left-0 top-full w-full pt-2 opacity-0 invisible group-hover/cat:opacity-100 group-hover/cat:visible transition-all duration-200 z-[100] cursor-default px-5 lg:px-8">
                    <div className="sg-card sg-card-lg sg-raise overflow-hidden max-h-[calc(100vh-140px)] overflow-y-auto scrollbar-thin">
                      <MegaMenuContent category={cat} />
                    </div>
                  </div>
                )}
              </div>
            ))}
          </nav>

          {/* Right icon row */}
          <div className="flex items-center gap-2.5 ml-auto lg:ml-0">
            <button
              onClick={() => setIsSearchOpen(!isSearchOpen)}
              className="at-focus sg-card rounded-full hidden md:flex items-center gap-2.5 px-5 h-[42px] text-[13.5px] font-medium text-soft hover:border-brand-300 transition-colors cursor-pointer min-w-[172px]"
              aria-label="Search"
            >
              <Search className="w-4 h-4" />
              <span>Search products</span>
            </button>
            <button
              onClick={() => setIsSearchOpen(!isSearchOpen)}
              className="at-focus sg-icon md:hidden cursor-pointer"
              aria-label="Search"
            >
              <Search className="w-[18px] h-[18px]" />
            </button>
            <button
              onClick={() => router.push("/wishlist")}
              className="at-focus sg-icon hidden sm:grid cursor-pointer"
              aria-label="Wishlist"
            >
              <svg className="w-[18px] h-[18px]" viewBox="0 0 24 24" stroke="currentColor" fill="none" strokeWidth="1.7">
                <path d="M12 20s-7-4.5-7-9a4 4 0 017-2.5A4 4 0 0119 11c0 4.5-7 9-7 9z" />
              </svg>
            </button>
            <button
              onClick={() => router.push("/account")}
              className="at-focus sg-icon cursor-pointer"
              aria-label="Account"
            >
              <svg className="w-[18px] h-[18px]" viewBox="0 0 24 24" stroke="currentColor" fill="none" strokeWidth="1.7">
                <circle cx="12" cy="8" r="3.6" />
                <path strokeLinecap="round" d="M4.5 20a7.5 7.5 0 0115 0" />
              </svg>
            </button>
            <Link href="/cart" className="at-focus sg-icon" aria-label="Cart">
              <svg className="w-[18px] h-[18px]" viewBox="0 0 24 24" stroke="currentColor" fill="none" strokeWidth="1.7">
                <path d="M6 8h12l-1 12H7L6 8z" />
                <path d="M9 8a3 3 0 016 0" />
              </svg>
              {cartItemsCount > 0 && (
                <span className="absolute -top-1 -right-1 min-w-[19px] h-[19px] px-1 bg-brand-600 text-white text-[10px] font-extrabold rounded-full flex items-center justify-center border-2 border-cream">
                  {cartItemsCount}
                </span>
              )}
            </Link>
          </div>

        </div>

      </header>

      {/* Full-screen Search Overlay (reference: SearchDrawer — dark blurred backdrop, underline input) */}
      {isSearchOpen && (
        <div
          className="fixed inset-0 z-100 flex items-start justify-center bg-brand-950/45 backdrop-blur-md pt-24 sm:pt-32 px-6 animate-in fade-in duration-200"
          onClick={() => setIsSearchOpen(false)}
        >
          <button
            onClick={() => setIsSearchOpen(false)}
            className="fixed top-5 right-5 sm:top-6 sm:right-6 z-110 sg-icon cursor-pointer"
            aria-label="Close search"
          >
            <X className="w-5 h-5" />
          </button>
          <form
            onSubmit={handleSearchSubmit}
            onClick={(e) => e.stopPropagation()}
            className="w-full max-w-3xl"
          >
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search for ..."
              className="w-full sg-card sg-raise rounded-full text-foreground placeholder-faint text-lg sm:text-xl font-medium px-8 py-5 outline-none focus:border-aqua-400 transition-colors"
              autoFocus
            />
          </form>
        </div>
      )}

      {/* Slide-out Mobile Navigation Drawer */}
      {isMenuOpen && (
        <div className="fixed inset-0 z-[100] flex">
          {/* Overlay */}
          <div
            className="fixed inset-0 bg-black/60 backdrop-blur-xs transition-opacity duration-300"
            onClick={() => setIsMenuOpen(false)}
          />

          {/* Sidebar content */}
          <div className="relative w-80 max-w-[85vw] bg-cream h-full flex flex-col shadow-2xl z-10 animate-in slide-in-from-left duration-300">
            {/* Header */}
            <div className="flex items-center justify-between border-b border-line px-6 py-5 shrink-0">
              <span className="text-base font-extrabold tracking-tight">{storeName}</span>
              <button
                onClick={() => setIsMenuOpen(false)}
                className="sg-icon w-9 h-9 cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Scrollable nav */}
            <nav className="flex-1 overflow-y-auto px-6 py-4 space-y-1">

              {/* Home */}
              <Link
                href="/"
                onClick={() => setIsMenuOpen(false)}
                className="block text-[14px] font-bold text-foreground hover:text-brand-700 py-3 border-b border-line"
              >
                Home
              </Link>

              {/* --- Dynamic API categories with multi-level accordion --- */}
              {categories.length > 0 && (
                <div className="pt-4 pb-1 border-b border-line">
                  {categories.map((cat) => {
                    const hasChildren = cat.children && cat.children.length > 0;
                    const isCatExpanded = !!expandedMobileCategories[cat.id];

                    return (
                      <div key={cat.id} className="border-b border-line last:border-0">
                        {hasChildren ? (
                          <>
                            {/* Category Accordion Header Row */}
                            <div className="flex items-center justify-between">
                              <Link
                                href={cat.url || `/category/${cat.slug}`}
                                onClick={() => setIsMenuOpen(false)}
                                className="text-[14px] font-semibold text-foreground hover:text-brand-700 py-3 transition-colors flex-1"
                              >
                                {cat.title || cat.name}
                              </Link>
                              <button
                                onClick={() => toggleMobileCategory(cat.id)}
                                className="p-3 text-faint hover:text-soft transition-colors cursor-pointer"
                                aria-label="Toggle Category"
                              >
                                {isCatExpanded ? (
                                  <ChevronUp className="w-4 h-4 text-faint" />
                                ) : (
                                  <ChevronDown className="w-4 h-4 text-faint" />
                                )}
                              </button>
                            </div>

                            {/* Category Accordion Content */}
                            {isCatExpanded && (
                              <div className="pl-4 pb-3 space-y-2.5 animate-in fade-in slide-in-from-top-1 duration-200">
                                {/* Subcategories */}
                                {cat.children.map((subCat: any) => {
                                  const hasSubChildren = subCat.children && subCat.children.length > 0;
                                  const isSubExpanded = !!expandedMobileSubCategories[subCat.id];

                                  return (
                                    <div key={subCat.id} className="pt-1">
                                      {hasSubChildren ? (
                                        <>
                                          {/* Subcategory Accordion Header Row */}
                                          <div className="flex items-center justify-between">
                                            <Link
                                              href={subCat.url || (subCat.slug === '#' ? '#' : `/category/${subCat.slug}`)}
                                              onClick={() => setIsMenuOpen(false)}
                                              className="text-[12.5px] font-bold text-soft hover:text-brand-700 py-2 flex-1"
                                            >
                                              {subCat.title || subCat.name}
                                            </Link>
                                            <button
                                              onClick={() => toggleMobileSubCategory(subCat.id)}
                                              className="p-2 text-faint hover:text-soft transition-colors cursor-pointer"
                                              aria-label="Toggle Subcategory"
                                            >
                                              {isSubExpanded ? (
                                                <ChevronUp className="w-3.5 h-3.5 text-faint" />
                                              ) : (
                                                <ChevronDown className="w-3.5 h-3.5 text-faint" />
                                              )}
                                            </button>
                                          </div>

                                          {/* Sub-subcategory links */}
                                          {isSubExpanded && (
                                            <div className="pl-3.5 py-1.5 space-y-2 border-l border-line ml-1.5 animate-in fade-in duration-200">
                                              {subCat.children.map((child: any) => {
                                                const slug = child.slug || child.url || '';
                                                const isDynamic = slug.includes('?') || slug.startsWith('shop') || slug.startsWith('pages');
                                                const href = child.url || (isDynamic ? `/${slug}` : `/category/${slug}`);

                                                return (
                                                  <Link
                                                    key={child.id}
                                                    href={href}
                                                    onClick={() => setIsMenuOpen(false)}
                                                    className="block text-[13px] text-soft hover:text-brand-700 transition-colors"
                                                  >
                                                    {child.title || child.name}
                                                  </Link>
                                                );
                                              })}
                                            </div>
                                          )}
                                        </>
                                      ) : (
                                        <Link
                                          href={subCat.url || (subCat.slug === '#' ? '#' : `/category/${subCat.slug}`)}
                                          onClick={() => setIsMenuOpen(false)}
                                          className="block text-[12.5px] font-bold text-soft hover:text-brand-700 py-1.5"
                                        >
                                          {subCat.title || subCat.name}
                                        </Link>
                                      )}
                                    </div>
                                  );
                                })}
                              </div>
                            )}
                          </>
                        ) : (
                          <Link
                            href={cat.url || `/category/${cat.slug}`}
                            onClick={() => setIsMenuOpen(false)}
                            className="block text-[14px] font-semibold text-foreground hover:text-brand-700 py-3 transition-colors"
                          >
                            {cat.title || cat.name}
                          </Link>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}

              {/* Account */}
              <Link
                href="/account"
                onClick={() => setIsMenuOpen(false)}
                className="flex items-center gap-2 text-[14px] font-bold text-foreground hover:text-brand-700 py-3 border-b border-line"
              >
                <User className="w-4 h-4" />
                My Account
              </Link>


              {/* Help (Mobile) */}
              <div className="pt-2 border-b border-line pb-3">
                <span className="block text-[14px] font-bold text-foreground py-3">
                  Help
                </span>
                <div className="space-y-2.5 pl-1">
                  {HELP_LINKS.map((item) => (
                    <Link
                      key={item.href}
                      href={item.href}
                      onClick={() => setIsMenuOpen(false)}
                      className="block text-[13px] text-soft hover:text-brand-700 transition-colors"
                    >
                      {item.label}
                    </Link>
                  ))}
                </div>
              </div>

              {/* Currency Selector (Mobile) */}
              <div className="pt-2">
                <button
                  onClick={() => {
                    setIsMenuOpen(false); // Close drawer to show modal
                    openCurrencyModal();
                  }}
                  className="w-full flex items-center justify-between text-[14px] font-bold text-foreground hover:text-brand-700 py-3 transition-colors cursor-pointer"
                >
                  <span className="flex items-center gap-2">
                    {selectedCountryCode && (
                      <img
                        src={`https://flagcdn.com/w40/${selectedCountryCode.toLowerCase()}.png`}
                        alt=""
                        className="w-4.5 h-3 object-cover rounded-lg shrink-0 border border-line/50"
                      />
                    )}
                    <span>Currency ({selectedCurrency?.symbol} {selectedCurrency?.code})</span>
                  </span>
                  <ChevronDown className="w-4 h-4 text-faint" />
                </button>
              </div>
            </nav>

            {/* Footer */}
            <div className="border-t border-line px-6 py-5 shrink-0">
              <span className="sg-kicker block mb-2">Need help?</span>
              <a href={`mailto:${settings["contact_email"] || "support@store.local"}`} className="text-[13px] text-soft hover:text-brand-700 transition-colors">
                {settings["contact_email"] || "support@store.local"}
              </a>
            </div>
          </div>
        </div>
      )}

      {/* 3. SLOW MOTION CURRENCY SELECTOR MODAL */}
      {isCurrencyModalOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 overflow-y-auto">
          {/* Backdrop Overlay */}
          <div
            className={`fixed inset-0 bg-black/60 backdrop-blur-xs transition-opacity duration-500 ease-out ${
              isModalAnimating ? "opacity-100" : "opacity-0"
            }`}
            onClick={closeCurrencyModal}
          />

          {/* Modal Box */}
          <div
            className={`bg-white w-full max-w-[420px] rounded-[24px] border border-line p-6 md:p-8 shadow-2xl relative z-10 transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] overflow-hidden ${
              isModalAnimating
                ? "opacity-100 scale-100 translate-y-0"
                : "opacity-0 scale-95 translate-y-8"
            }`}
          >
            {/* Modal Header */}
            <div className="flex items-center justify-between border-b border-line pb-4 mb-4 text-left">
              <span className="text-[11px] font-bold text-soft uppercase tracking-[0.14em] flex items-center gap-2">
                {selectedCountryCode && (
                  <img
                    src={`https://flagcdn.com/w40/${selectedCountryCode.toLowerCase()}.png`}
                    alt=""
                    className="w-4.5 h-3 object-cover rounded-lg shrink-0 border border-line/50"
                  />
                )}
                <span>{selectedCountry} ({selectedCurrency?.symbol} {selectedCurrency?.code})</span>
              </span>
              <button
                onClick={closeCurrencyModal}
                className="p-1.5 text-faint hover:text-brand-700 hover:bg-cream rounded-xl transition cursor-pointer"
                aria-label="Close modal"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Modal Content */}
            <div className="text-left">
              <h3 className="text-sm font-extrabold uppercase tracking-wider text-foreground mb-1">
                Select your shipping location.
              </h3>
              <p className="text-[9px] sm:text-[10px] font-bold text-faint uppercase tracking-[0.14em] leading-relaxed mb-5">
                YOUR CURRENT SELECTED LOCATION IS {selectedCountry?.toUpperCase()} AND YOUR ORDER WILL BE BILLED IN {selectedCurrency?.code}
              </p>

              {/* Country Search Bar */}
              <div className="relative mb-5">
                <Search className="w-4 h-4 text-faint absolute left-4 top-1/2 -translate-y-1/2" />
                <input
                  type="text"
                  placeholder="Search for a delivery location"
                  value={countrySearchQuery}
                  onChange={(e) => setCountrySearchQuery(e.target.value)}
                  className="w-full bg-cream hover:bg-brand-50 focus:bg-white text-foreground placeholder-faint font-bold text-xs rounded-sg pl-11 pr-4 py-3 border border-transparent focus:border-line focus:outline-none transition-all"
                />
              </div>

              {/* Scrollable List */}
              <div className="max-h-[320px] overflow-y-auto pr-1 scrollbar-thin space-y-2">
                {countrySearchQuery.trim() === "" ? (
                  // Continent Accordions
                  CONTINENTS.map((group) => {
                    const isOpen = !!expandedContinents[group.name];
                    return (
                      <div key={group.name} className="border-b border-line pb-2 last:border-0 last:pb-0">
                        {/* Continent Header Toggle */}
                        <button
                          onClick={() => toggleContinent(group.name)}
                          className="w-full flex items-center justify-between py-3 text-left cursor-pointer group"
                        >
                          <span className="text-[10px] font-extrabold uppercase tracking-[0.14em] text-foreground group-hover:text-brand-700 transition-colors">
                            {group.name}
                          </span>
                          {isOpen ? (
                            <ChevronUp className="w-3.5 h-3.5 text-faint group-hover:text-soft transition-colors" />
                          ) : (
                            <ChevronDown className="w-3.5 h-3.5 text-faint group-hover:text-soft transition-colors" />
                          )}
                        </button>

                        {/* Countries List */}
                        {isOpen && (
                          <div className="pl-2 pr-1 py-1 space-y-1.5 animate-in fade-in duration-250">
                            {group.countries.map((country) => {
                              const isSelected = selectedCountry === country.name;
                              return (
                                <button
                                  key={country.name}
                                  onClick={() => handleCountrySelect(country.name, country.currency)}
                                  className={`w-full text-left py-2 px-3 text-xs font-bold rounded-xl transition-all flex justify-between items-center cursor-pointer ${
                                    isSelected
                                      ? "bg-brand-600 rounded-full text-white"
                                      : "bg-transparent text-soft hover:text-brand-700 hover:bg-cream"
                                  }`}
                                >
                                  <span className="flex items-center gap-2">
                                    <img
                                      src={`https://flagcdn.com/w20/${country.code.toLowerCase()}.png`}
                                      alt=""
                                      className="w-4 h-3 object-cover rounded-lg shrink-0 border border-line"
                                    />
                                    <span>{country.name}</span>
                                  </span>
                                  <span className="text-[10px] font-mono opacity-80">
                                    ({country.currency})
                                  </span>
                                </button>
                              );
                            })}
                          </div>
                        )}
                      </div>
                    );
                  })
                ) : (
                  // Search Results
                  <div className="space-y-1.5">
                    {searchResults.length === 0 ? (
                      <div className="text-center py-6 text-xs font-bold text-faint uppercase tracking-wider">
                        No locations found
                      </div>
                    ) : (
                      searchResults.map((country) => {
                        const isSelected = selectedCountry === country.name;
                        return (
                          <button
                            key={country.name}
                            onClick={() => handleCountrySelect(country.name, country.currency)}
                            className={`w-full text-left py-2 px-3 text-xs font-bold rounded-xl transition-all flex justify-between items-center cursor-pointer ${
                              isSelected
                                ? "bg-brand-600 rounded-full text-white"
                                : "bg-transparent text-soft hover:text-brand-700 hover:bg-cream"
                            }`}
                          >
                            <span className="flex items-center gap-2">
                              <img
                                src={`https://flagcdn.com/w20/${country.code.toLowerCase()}.png`}
                                alt=""
                                className="w-4 h-3 object-cover rounded-lg shrink-0 border border-line"
                              />
                              <span>{country.name}</span>
                            </span>
                            <span className="text-[10px] font-mono opacity-80">
                              ({country.currency})
                            </span>
                          </button>
                        );
                      })
                    )}
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
