"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import Image from "next/image";
import { useRouter, usePathname } from "next/navigation";
import {
  Search,
  User,
  Menu,
  X,
  ArrowRight,
  ChevronDown,
  ChevronUp
} from "lucide-react";
import { getCart } from "@/lib/cart";
import { useCurrency, CONTINENTS } from "@/providers/CurrencyProvider";
import { useSettings } from "@/providers/SettingsProvider";
import { HELP_LINKS } from "@/lib/helpLinks";

interface Category {
  id: string;
  name: string;
  slug: string;
  image?: string | null;
  children?: Category[];
}

interface HeaderProps {
  categories?: Category[];
}

// ─── About mega menu ──────────────────────────────────────────────────────────
// A different shape from the shop menus: one narrow column of text links on the
// left, then a row of large portrait image tiles with the label set over the
// image. Tiles are driven by `MenuItem.imageUrl`, so which entries get a tile —
// and which picture they use — stays editable from Admin → Menus.
function AboutMenuContent({ category, storeName }: { category: any; storeName: string }) {
  const items: any[] = category.children || [];

  // The bold heading doubles as the link to the main About page, mirroring the
  // reference. When such an entry exists it is lifted out of the list below so
  // the same destination isn't offered twice.
  const aboutIndex = items.findIndex(
    (i) => /^about/i.test(i.title || i.name || "") || (i.url || "") === "/pages/about-us"
  );
  const aboutEntry = aboutIndex >= 0 ? items[aboutIndex] : null;
  const links = aboutIndex >= 0 ? items.filter((_, idx) => idx !== aboutIndex) : items;

  const tiles = items.filter((i) => i.imageUrl);

  // Root title is usually just "About", so the brand name is appended to match
  // the reference's "About American Tall". A title that already says more than
  // that is left alone.
  const rootTitle = category.title || category.name || "About";
  const heading =
    /^about$/i.test(rootTitle.trim()) && storeName && storeName !== "My Store"
      ? `About ${storeName}`
      : rootTitle;

  const headingClass = "text-base font-bold tracking-tight text-zinc-950";

  return (
    <div className="max-w-[1600px] mx-auto px-4 xl:px-8 py-8 flex flex-col lg:flex-row gap-8 xl:gap-12 w-full">
      {/* Left: heading + text links */}
      <div className="w-full lg:w-[230px] xl:w-[270px] shrink-0">
        {aboutEntry ? (
          <Link href={aboutEntry.url || "/pages/about-us"} className={`${headingClass} block w-fit hover:text-zinc-600 transition-colors`}>
            {heading}
          </Link>
        ) : (
          <p className={headingClass}>{heading}</p>
        )}

        <ul className="mt-6 flex flex-col gap-4">
          {links.map((item) => (
            <li key={item.id}>
              <Link
                href={item.url || "#"}
                className="relative inline-block text-[15px] font-medium text-zinc-500 hover:text-zinc-950 transition-colors after:absolute after:bottom-0 after:left-0 after:h-px after:w-0 after:bg-zinc-950 after:transition-[width] after:duration-300 after:ease-out hover:after:w-full"
              >
                {item.title || item.name}
              </Link>
            </li>
          ))}
        </ul>
      </div>

      {/* Right: image tiles. Column count is inline rather than a Tailwind class
          because it depends on runtime data — an interpolated `grid-cols-${n}`
          would never be generated by Tailwind's static scan. */}
      {tiles.length > 0 && (
        <div
          className="grid flex-1 gap-3 xl:gap-4"
          style={{ gridTemplateColumns: `repeat(${tiles.length}, minmax(0, 1fr))` }}
        >
          {tiles.map((tile) => (
            <Link
              key={tile.id}
              href={tile.url || "#"}
              className="group/tile relative block aspect-[3/4] overflow-hidden bg-zinc-100"
            >
              <Image
                src={tile.imageUrl}
                alt={tile.title || tile.name || ""}
                fill
                sizes="(max-width: 1024px) 50vw, 30vw"
                className="object-cover transition-transform duration-700 ease-out group-hover/tile:scale-105"
              />
              <div className="absolute inset-0 bg-black/10 transition-colors group-hover/tile:bg-black/25" />
              <span className="absolute inset-0 flex items-center justify-center px-4 text-center text-xl xl:text-2xl font-black tracking-tight text-white drop-shadow-[0_2px_8px_rgba(0,0,0,0.45)]">
                {tile.title || tile.name}
              </span>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}

function MegaMenuContent({ category }: { category: any }) {
  const { storeName } = useSettings();

  // Only use database-driven columns (children of the main category)
  const columns = category.children || [];

  const titleLower = (category.title || category.name || "").toLowerCase();
  const urlLower = (category.url || "").toLowerCase();

  // The About tree is a flat list of editorial pages, not a category hierarchy,
  // so it gets the tile layout instead of the four-column shop grid.
  if (titleLower === "about" || titleLower.startsWith("about ")) {
    return <AboutMenuContent category={category} storeName={storeName} />;
  }

  const isShopMenu =
    category.slug === 'man' || 
    category.slug === 'woman' || 
    category.slug === 'mens' || 
    category.slug === 'womens' ||
    titleLower === 'man' ||
    titleLower === 'woman' ||
    titleLower === 'men' ||
    titleLower === 'women' ||
    urlLower === '/category/man' ||
    urlLower === '/category/woman' ||
    urlLower.includes('category=man') ||
    urlLower.includes('category=woman');

  const hasImage = !!(category.imageUrl || category.categoryImage || category.image || isShopMenu);

  // `categoryImage` is the card image of the Category this menu item points at,
  // resolved in Header.tsx. It sits ahead of the stock photos so a category the
  // admin has already illustrated shows its own artwork here; the Unsplash pair
  // only covers a shop menu whose category has no image at all.
  const imageUrl = category.imageUrl || category.categoryImage || category.image || (category.slug === 'women' || titleLower === 'woman' || titleLower === 'women' || urlLower.includes('woman') || urlLower.includes('women')
    ? "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800"
    : "https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&q=80&w=800");

  // Group the columns into 4 vertical columns as requested
  const groupedColumns: any[][] = [[], [], [], []];
  
  if (isShopMenu) {
    columns.forEach((col: any) => {
      const name = (col.title || col.name || "").toLowerCase();
      if (name.includes("featured") || name.includes("sale")) {
        groupedColumns[0].push(col);
      } else if (name.includes("top") || name.includes("dress") || name.includes("accessory") || name.includes("accessories")) {
        groupedColumns[1].push(col);
      } else if (name.includes("bottom") || name.includes("footwear") || name.includes("shoe") || name.includes("specialty")) {
        groupedColumns[2].push(col);
      } else {
        groupedColumns[3].push(col);
      }
    });
  } else {
    // Just distribute sequentially starting from the left (Column 1)
    columns.forEach((col: any, idx: number) => {
      groupedColumns[idx % 4].push(col);
    });
  }

  return (
    <div className="max-w-[1600px] mx-auto px-4 xl:px-8 py-6 flex justify-between gap-6 xl:gap-8 w-full overflow-hidden">
      {/* Left Link Columns Container */}
      <div className="grid grid-cols-4 gap-y-8 gap-x-6 xl:gap-x-12 flex-1">
        {groupedColumns.map((colGroup, groupIdx) => (
          <div key={groupIdx} className="flex flex-col gap-6">
            {colGroup.map((col: any) => (
              <div key={col.id} className="flex flex-col gap-2">
                <Link href={col.url || (col.slug === '#' ? '#' : `/category/${col.slug}`)} className="relative font-semibold text-zinc-950 text-base capitalize block w-fit after:absolute after:bottom-0 after:left-0 after:h-px after:w-0 after:bg-zinc-950 after:transition-[width] after:duration-300 after:ease-out hover:after:w-full">
                  {col.title || col.name}
                </Link>
                {col.children && col.children.length > 0 && (
                  <ul className="space-y-2 text-zinc-500 text-[13px]">
                    {col.children.map((child: any) => {
                      // Check if it's a dynamic link (contains ? or starts with 'shop' or 'pages')
                      const slug = child.slug || child.url || '';
                      const isDynamic = slug.includes('?') || slug.startsWith('shop') || slug.startsWith('pages');
                      const href = child.url || (isDynamic ? `/${slug}` : `/category/${slug}`);
                      return (
                        <li key={child.id}>
                          <Link href={href} className="relative inline-block hover:text-zinc-950 transition-colors after:absolute after:bottom-0 after:left-0 after:h-px after:w-0 after:bg-zinc-950 after:transition-[width] after:duration-300 after:ease-out hover:after:w-full">
                            {child.title || child.name}
                          </Link>
                        </li>
                      );
                    })}
                  </ul>
                )}
              </div>
            ))}
          </div>
        ))}
      </div>

      {/* Right Image Container */}
      {hasImage && (
        <div className="w-[220px] xl:w-[260px] shrink-0">
          <Link href={category.url || `/category/${category.slug}`} className="block relative w-full aspect-[4/5] group/image overflow-hidden bg-zinc-100">
            <Image 
              src={imageUrl} 
              alt={category.title || category.name || "Category"} 
              fill
              className="object-cover group-hover/image:scale-105 transition-transform duration-700 ease-out" 
            />
            <div className="absolute inset-0 flex items-center justify-center bg-black/20">
              <span className="text-white text-lg xl:text-xl font-black tracking-wide drop-shadow-lg text-center px-4">
                Shop {category.title || category.name}
              </span>
            </div>
          </Link>
        </div>
      )}
    </div>
  );
}

export default function HeaderClient({ menus, transparent = false }: { menus?: any[]; transparent?: boolean }) {
  const router = useRouter();
  const pathname = usePathname();
  const { storeName, settings } = useSettings();

  const logoSrc = settings["brand_logo_url"] || "/logo.svg";
  const logoIsSvg = /\.svg(\?|$)/i.test(logoSrc);

  // One round action chip. `grid` rather than `flex` so the callers that need
  // to hide one on small screens can swap in `hidden sm:grid` without the
  // display mode fighting the centring.
  const sigIcon =
    "grid h-10 w-10 shrink-0 place-items-center rounded-full border border-sig-line bg-sig-card text-sig-ink transition-colors hover:border-sig-copper-400 cursor-pointer lg:h-[42px] lg:w-[42px]";

  const [categories, setCategories] = useState<any[]>(menus || []);
  const [cartItemsCount, setCartItemsCount] = useState(0);
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isSearchOpen, setIsSearchOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  
  // Brand Settings. Read straight off the settings context — the root layout
  // already loaded these on the server. This used to be state filled by a
  // `/api/settings` fetch on mount, which made it the third request for that
  // same endpoint on every page load, for one string.
  // `liveSlogan` only holds a value after an admin save (see the listener below).
  const [liveSlogan, setLiveSlogan] = useState<string | null>(null);
  const brandSlogan =
    liveSlogan ?? settings["brand_slogan"] ?? "Tall Men 6' - 7'1\" | Tall Women 5'9\" - 6'6\"";

  // Shrink header/logo once the page is scrolled
  const [isScrolled, setIsScrolled] = useState(false);

  // Transparent mode: solid again on hover so the mega menu stays readable
  const [isHovered, setIsHovered] = useState(false);
  const isOverlay = transparent && !isScrolled && !isHovered && !isSearchOpen;

  /**
   * The logo links home, but on the home page itself a Link to the current
   * route is a no-op in the App Router — the click registers and nothing
   * happens, which reads as a broken logo. Scroll back to the top instead,
   * which is what tapping the mark is expected to do once you are already home.
   */
  const handleHomeClick = (e: React.MouseEvent) => {
    setIsMenuOpen(false);
    setIsSearchOpen(false);
    if (pathname !== "/") return;
    e.preventDefault();
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const { 
    currencies, 
    selectedCurrency, 
    setCurrency, 
    selectedCountry, 
    setCountryAndCurrency 
  } = useCurrency();

  const selectedCountryInfo = CONTINENTS.flatMap((g) => g.countries).find(
    (c) => c.name === selectedCountry
  );
  const selectedCountryCode = selectedCountryInfo?.code || "";

  // Currency modal states
  const [isCurrencyModalOpen, setIsCurrencyModalOpen] = useState(false);
  const [isModalAnimating, setIsModalAnimating] = useState(false);
  const [countrySearchQuery, setCountrySearchQuery] = useState("");
  const [expandedContinents, setExpandedContinents] = useState<Record<string, boolean>>({ ASIA: true }); // Default ASIA open since Bangladesh is there

  // Mobile accordion expansion states
  const [expandedMobileCategories, setExpandedMobileCategories] = useState<Record<string, boolean>>({});
  const [expandedMobileSubCategories, setExpandedMobileSubCategories] = useState<Record<string, boolean>>({});

  const toggleMobileCategory = (id: string) => {
    setExpandedMobileCategories(prev => ({
      ...prev,
      [id]: !prev[id]
    }));
  };

  const toggleMobileSubCategory = (id: string) => {
    setExpandedMobileSubCategories(prev => ({
      ...prev,
      [id]: !prev[id]
    }));
  };

  const openCurrencyModal = () => {
    setIsCurrencyModalOpen(true);
    setCountrySearchQuery("");
    requestAnimationFrame(() => {
      setIsModalAnimating(true);
    });
  };

  const closeCurrencyModal = () => {
    setIsModalAnimating(false);
    setTimeout(() => {
      setIsCurrencyModalOpen(false);
    }, 500); // match duration-500
  };

  const toggleContinent = (name: string) => {
    setExpandedContinents(prev => ({
      ...prev,
      [name]: !prev[name]
    }));
  };

  const handleCountrySelect = (countryName: string, currencyCode: string) => {
    setCountryAndCurrency(countryName, currencyCode);
    closeCurrencyModal();
  };

  const searchResults = CONTINENTS.flatMap((g) => g.countries)
    .filter((c) => c.name.toLowerCase().includes(countrySearchQuery.toLowerCase()));

  // Fetch menus if not passed as prop
  useEffect(() => {
    if (menus && menus.length > 0) {
      setCategories(menus);
      return;
    }

    const fetchMenus = async () => {
      try {
        const res = await fetch("/api/menus");
        if (res.ok) {
          const data = await res.json();
          setCategories(data);
        }
      } catch (err) {
        console.error("Failed to fetch header menus:", err);
      }
    };
    fetchMenus();
  }, [menus]);

  // Real-time update when saving from admin. No fetch on mount any more — the
  // slogan is already in the settings context; this only runs when the admin
  // settings screen announces a save.
  useEffect(() => {
    const handleUpdate = async () => {
      try {
        const res = await fetch("/api/settings");
        if (res.ok) {
          const data = await res.json();
          if (data.brand_slogan) setLiveSlogan(data.brand_slogan);
        }
      } catch (err) {
        console.error("Failed to refresh brand settings:", err);
      }
    };
    window.addEventListener("brand-settings-updated", handleUpdate);
    return () => window.removeEventListener("brand-settings-updated", handleUpdate);
  }, []);

  // Shrink header/logo once the page is scrolled
  useEffect(() => {
    const handleScroll = () => setIsScrolled(window.scrollY > 20);
    handleScroll();
    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  // Sync cart count
  useEffect(() => {
    const updateCartCount = () => {
      const cart = getCart();
      const count = cart.reduce((sum, item) => sum + item.quantity, 0);
      setCartItemsCount(count);
    };

    updateCartCount();
    window.addEventListener("cart-updated", updateCartCount);
    window.addEventListener("storage", updateCartCount);

    return () => {
      window.removeEventListener("cart-updated", updateCartCount);
      window.removeEventListener("storage", updateCartCount);
    };
  }, []);

  // Close menus on page transition
  useEffect(() => {
    setIsMenuOpen(false);
    setIsSearchOpen(false);
  }, [pathname]);

  // Full-screen search overlay: Escape to close, lock body scroll while open
  useEffect(() => {
    if (!isSearchOpen) return;
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setIsSearchOpen(false);
    };
    window.addEventListener("keydown", handleKey);
    document.body.style.overflow = "hidden";
    return () => {
      window.removeEventListener("keydown", handleKey);
      document.body.style.overflow = "";
    };
  }, [isSearchOpen]);

  const handleSearchSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (searchQuery.trim()) {
      router.push(`/shop?query=${encodeURIComponent(searchQuery.trim())}`);
      setIsSearchOpen(false);
      setSearchQuery("");
    }
  };

  return (
    <>
      {/* 1. TOP UTILITY BAR */}
      <div className="w-full bg-sig-copper-50 text-sig-ink py-2 px-4 text-[10px] sm:text-[11px] font-medium tracking-wide border-b border-sig-line z-60 relative flex justify-between items-center">
        <div className="hidden md:flex flex-1"></div>
        <div className="flex-1 text-center whitespace-nowrap font-semibold text-[12px]">
          {brandSlogan}
        </div>
        <div className="hidden md:flex flex-1 justify-end items-center space-x-6">
          <button
            onClick={openCurrencyModal}
            className="hover:text-zinc-500 transition-colors font-bold uppercase tracking-wide flex items-center gap-2 cursor-pointer"
          >
            {selectedCountryCode && (
              <img
                src={`https://flagcdn.com/w40/${selectedCountryCode.toLowerCase()}.png`}
                alt=""
                className="w-4.5 h-3 object-cover rounded-xs shrink-0 border border-zinc-200/50"
              />
            )}
            <span>CURRENCY ({selectedCurrency?.symbol} {selectedCurrency?.code})</span>
          </button>
          {/* Help dropdown */}
          <div className="relative group/help">
            <Link
              href="/pages/help-center"
              className="hover:text-zinc-500 transition-colors font-bold uppercase tracking-wide flex items-center gap-1 py-1"
            >
              HELP
            </Link>

            <div className="absolute right-0 top-full pt-2 opacity-0 invisible translate-y-1 group-hover/help:opacity-100 group-hover/help:visible group-hover/help:translate-y-0 focus-within:opacity-100 focus-within:visible focus-within:translate-y-0 transition-all duration-200 z-[110]">
              <ul className="min-w-[240px] bg-white border border-zinc-200 shadow-xl py-2 text-left">
                {HELP_LINKS.map((item) => (
                  <li key={item.href}>
                    <Link
                      href={item.href}
                      className="block px-6 py-2.5 text-[14px] font-normal text-zinc-800 hover:bg-zinc-50 hover:text-zinc-950 transition-colors whitespace-nowrap"
                    >
                      {item.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </div>

      {/* 2. PREMIUM NAVIGATION HEADER */}
      {/* `transform: translateZ(0)` forces this onto its own GPU compositing
          layer. iOS Safari has a known bug where a `position: sticky` element
          is occasionally left painted at a stale scroll offset — visually
          detached mid-page — until something forces a repaint; promoting it
          to its own layer is the standard workaround. */}
      <header
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
        style={{ transform: "translateZ(0)", WebkitBackfaceVisibility: "hidden" }}
        className={`sticky top-0 z-50 w-full transition-all duration-300 ${
          isOverlay
            ? "at-header-overlay bg-transparent"
            : "bg-sig-cream/90 backdrop-blur-[14px] border-b border-sig-line"
        }`}
      >
        {/* Signature bar: mark on the left, the nav as a floating pill centred
            between them, and the actions as round chips on the right. */}
        <div className="sig-wrap flex items-center gap-3 py-3 lg:gap-6">

          {/* Menu Icon (Mobile) */}
          <button
            onClick={() => setIsMenuOpen(true)}
            className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-sig-line bg-sig-card text-sig-ink transition-colors hover:border-sig-copper-400 cursor-pointer lg:hidden"
            aria-label="Open Menu"
          >
            <Menu className="w-5 h-5" />
          </button>

          {/* Logo */}
          {/* `unoptimized` for SVG sources: next/image refuses to run SVG
              through the optimizer unless `dangerouslyAllowSVG` is on, so both
              an uploaded .svg logo and the /logo.svg fallback came back 400 and
              the header rendered with no mark at all. A vector gains nothing
              from re-encoding anyway; raster logos still get optimized.

              Fixed width/height rather than `fill`: `fill` makes the <img>
              `position: absolute`, and iOS Safari has a bug where an absolutely
              positioned descendant of a `position: sticky` element gets left
              painted mid-page as you scroll — which is why the mark was showing
              up floating in the middle of pages on mobile. An in-flow image
              inside the sticky header does not hit that bug. */}
          <Link
            href="/"
            onClick={handleHomeClick}
            className="hover:opacity-90 transition-opacity flex-shrink-0"
          >
            <Image
              src={logoSrc}
              alt={storeName}
              width={144}
              height={48}
              className="h-10 w-auto max-w-[8rem] object-contain lg:h-12 lg:max-w-[9rem]"
              unoptimized={logoIsSvg}
              priority
            />
          </Link>

          {/* Nav pill. `mx-auto` on the middle flex child is what centres it
              between the mark and the actions — the same trick the reference
              uses — so it stays centred regardless of how wide the logo is.
              The mega menu is still positioned against <header> (sticky counts
              as positioned), so it spans the full width, not the pill. */}
          <nav className="mx-auto hidden items-center gap-1 rounded-full border border-sig-line bg-sig-card p-1.5 lg:flex">
            {categories.map((cat) => (
              <div key={cat.id} className="group/cat flex items-center">
                <Link
                  href={cat.url || `/category/${cat.slug}`}
                  className="whitespace-nowrap rounded-full px-4 py-2.5 text-sm font-semibold text-sig-soft transition-colors hover:bg-sig-copper-50 hover:text-sig-ink xl:px-[18px]"
                >
                  {cat.title || cat.name}
                </Link>

                {/* Dropdown Container */}
                {cat.children && cat.children.length > 0 && (
                  <div className="absolute left-0 top-full w-full bg-white shadow-xl opacity-0 invisible group-hover/cat:opacity-100 group-hover/cat:visible transition-all duration-200 z-[100] border-t border-sig-line pb-12 cursor-default max-h-[calc(100vh-110px)] overflow-y-auto scrollbar-thin">
                    <MegaMenuContent category={cat} />
                  </div>
                )}
              </div>
            ))}
          </nav>

          {/* Right header actions — round chips, per the reference's 42px icons */}
          <div className="ml-auto flex items-center justify-end gap-2 lg:ml-0">
            <button
              onClick={() => setIsSearchOpen(!isSearchOpen)}
              className={sigIcon}
              aria-label="Search"
            >
              <Search className="w-[19px] h-[19px]" />
            </button>
            <button
              onClick={() => router.push("/wishlist")}
              className={`${sigIcon} hidden sm:grid`}
              aria-label="Wishlist"
            >
              <svg
                className="w-5 h-5"
                viewBox="0 0 15 20"
                xmlns="http://www.w3.org/2000/svg"
                stroke="currentColor"
                fill="none"
              >
                <path d="M14.0132 19.28L7.13317 14.45L0.253174 19.28V0.720001H14.0132V19.28Z" fill="none" />
              </svg>
            </button>
            <button
              onClick={() => router.push("/account")}
              className={sigIcon}
              aria-label="Account"
            >
              <svg
                className="w-5 h-5"
                viewBox="0 0 24 24"
                stroke="currentColor"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <rect width="10.5" height="10.5" x="6.75" y="1.75" rx="5.25" />
                <path
                  strokeLinecap="round"
                  d="M12 15.5c1.5 0 4 .333 4.5.5.5.167 3.7.8 4.5 2 1 1.5 1 2 1 4m-10-6.5c-1.5 0-4 .333-4.5.5-.5.167-3.7.8-4.5 2-1 1.5-1 2-1 4"
                />
              </svg>
            </button>
            <Link
              href="/cart"
              className={`${sigIcon} relative`}
              aria-label="Cart"
            >
              <svg
                className="w-5 h-5"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 18 17"
                fill="currentColor"
              >
                <path
                  fillRule="evenodd"
                  clipRule="evenodd"
                  d="M6.04167 0.875C5.48938 0.875 5.04167 1.32272 5.04167 1.875V3.20833C5.04167 3.76062 4.59395 4.20833 4.04167 4.20833H1.875C1.32272 4.20833 0.875 4.65605 0.875 5.20833V15.2917C0.875 15.844 1.32272 16.2917 1.875 16.2917H16.125C16.6773 16.2917 17.125 15.844 17.125 15.2917V5.20833C17.125 4.65605 16.6773 4.20833 16.125 4.20833H13.9583C13.406 4.20833 12.9583 3.76062 12.9583 3.20833V1.875C12.9583 1.32271 12.5106 0.875 11.9583 0.875H6.04167ZM7.29167 4.20833C6.73938 4.20833 6.29167 3.76062 6.29167 3.20833V3.125C6.29167 2.57272 6.73938 2.125 7.29167 2.125H10.7083C11.2606 2.125 11.7083 2.57272 11.7083 3.125V3.20833C11.7083 3.76062 11.2606 4.20833 10.7083 4.20833H7.29167ZM16 5.5H2V15H16V5.5Z"
                />
              </svg>
              {cartItemsCount > 0 && (
                <span className="absolute -top-1 -right-1 grid h-[19px] min-w-[19px] place-items-center rounded-full border-2 border-sig-cream bg-sig-copper-600 px-1 text-[10px] font-extrabold text-white">
                  {cartItemsCount}
                </span>
              )}
            </Link>
          </div>

        </div>

      </header>

      {/* Full-screen Search Overlay (reference: SearchDrawer — dark blurred backdrop, underline input) */}
      {isSearchOpen && (
        <div
          className="fixed inset-0 z-100 flex items-start justify-center bg-at-ink/50 backdrop-blur-md pt-24 sm:pt-32 px-6 animate-in fade-in duration-200"
          onClick={() => setIsSearchOpen(false)}
        >
          <button
            onClick={() => setIsSearchOpen(false)}
            className="fixed top-5 right-5 sm:top-6 sm:right-6 z-110 flex items-center justify-center w-10 h-10 bg-white text-zinc-950 hover:bg-zinc-100 transition-colors cursor-pointer"
            aria-label="Close search"
          >
            <X className="w-5 h-5" />
          </button>
          <form
            onSubmit={handleSearchSubmit}
            onClick={(e) => e.stopPropagation()}
            className="w-full max-w-3xl"
          >
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search for ..."
              className="w-full bg-white/15 backdrop-blur-sm border-b border-white/60 focus:border-white text-white placeholder-white/70 text-xl sm:text-2xl font-light px-5 py-4 outline-none transition-colors"
              autoFocus
            />
          </form>
        </div>
      )}

      {/* Slide-out Mobile Navigation Drawer */}
      {isMenuOpen && (
        <div className="fixed inset-0 z-[100] flex">
          {/* Overlay */}
          <div
            className="fixed inset-0 bg-black/60 backdrop-blur-xs transition-opacity duration-300"
            onClick={() => setIsMenuOpen(false)}
          />

          {/* Sidebar content */}
          <div className="relative w-80 max-w-[85vw] bg-white h-full flex flex-col shadow-2xl z-10 animate-in slide-in-from-left duration-300">
            {/* Header */}
            <div className="flex items-center justify-between border-b border-zinc-100 px-6 py-5 shrink-0">
              <span className="text-sm font-black tracking-widest uppercase">{storeName}</span>
              <button
                onClick={() => setIsMenuOpen(false)}
                className="p-1 text-zinc-500 hover:text-zinc-950 cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Scrollable nav */}
            <nav className="flex-1 overflow-y-auto px-6 py-4 space-y-1">

              {/* Home */}
              <Link
                href="/"
                onClick={handleHomeClick}
                className="block text-[11px] font-bold tracking-widest uppercase text-zinc-800 hover:text-zinc-950 py-3 border-b border-zinc-100"
              >
                Home
              </Link>

              {/* --- Dynamic API categories with multi-level accordion --- */}
              {categories.length > 0 && (
                <div className="pt-4 pb-1 border-b border-zinc-100">
                  {categories.map((cat) => {
                    const hasChildren = cat.children && cat.children.length > 0;
                    const isCatExpanded = !!expandedMobileCategories[cat.id];

                    return (
                      <div key={cat.id} className="border-b border-zinc-50 last:border-0">
                        {hasChildren ? (
                          <>
                            {/* Category Accordion Header Row */}
                            <div className="flex items-center justify-between">
                              <Link
                                href={cat.url || `/category/${cat.slug}`}
                                onClick={() => setIsMenuOpen(false)}
                                className="text-[12px] font-medium text-zinc-700 hover:text-zinc-950 py-3 transition-colors flex-1"
                              >
                                {cat.title || cat.name}
                              </Link>
                              <button
                                onClick={() => toggleMobileCategory(cat.id)}
                                className="p-3 text-zinc-400 hover:text-zinc-600 transition-colors cursor-pointer"
                                aria-label="Toggle Category"
                              >
                                {isCatExpanded ? (
                                  <ChevronUp className="w-4 h-4 text-zinc-400" />
                                ) : (
                                  <ChevronDown className="w-4 h-4 text-zinc-400" />
                                )}
                              </button>
                            </div>

                            {/* Category Accordion Content */}
                            {isCatExpanded && (
                              <div className="pl-4 pb-3 space-y-2.5 animate-in fade-in slide-in-from-top-1 duration-200">
                                {/* Subcategories */}
                                {cat.children.map((subCat: any) => {
                                  const hasSubChildren = subCat.children && subCat.children.length > 0;
                                  const isSubExpanded = !!expandedMobileSubCategories[subCat.id];

                                  return (
                                    <div key={subCat.id} className="pt-1">
                                      {hasSubChildren ? (
                                        <>
                                          {/* Subcategory Accordion Header Row */}
                                          <div className="flex items-center justify-between">
                                            <Link
                                              href={subCat.url || (subCat.slug === '#' ? '#' : `/category/${subCat.slug}`)}
                                              onClick={() => setIsMenuOpen(false)}
                                              className="text-[11px] font-bold uppercase tracking-wider text-zinc-500 hover:text-zinc-950 py-2 flex-1"
                                            >
                                              {subCat.title || subCat.name}
                                            </Link>
                                            <button
                                              onClick={() => toggleMobileSubCategory(subCat.id)}
                                              className="p-2 text-zinc-400 hover:text-zinc-600 transition-colors cursor-pointer"
                                              aria-label="Toggle Subcategory"
                                            >
                                              {isSubExpanded ? (
                                                <ChevronUp className="w-3.5 h-3.5 text-zinc-400" />
                                              ) : (
                                                <ChevronDown className="w-3.5 h-3.5 text-zinc-400" />
                                              )}
                                            </button>
                                          </div>

                                          {/* Sub-subcategory links */}
                                          {isSubExpanded && (
                                            <div className="pl-3.5 py-1.5 space-y-2 border-l border-zinc-100 ml-1.5 animate-in fade-in duration-200">
                                              {subCat.children.map((child: any) => {
                                                const slug = child.slug || child.url || '';
                                                const isDynamic = slug.includes('?') || slug.startsWith('shop') || slug.startsWith('pages');
                                                const href = child.url || (isDynamic ? `/${slug}` : `/category/${slug}`);

                                                return (
                                                  <Link
                                                    key={child.id}
                                                    href={href}
                                                    onClick={() => setIsMenuOpen(false)}
                                                    className="block text-[11px] text-zinc-500 hover:text-zinc-950 transition-colors"
                                                  >
                                                    {child.title || child.name}
                                                  </Link>
                                                );
                                              })}
                                            </div>
                                          )}
                                        </>
                                      ) : (
                                        <Link
                                          href={subCat.url || (subCat.slug === '#' ? '#' : `/category/${subCat.slug}`)}
                                          onClick={() => setIsMenuOpen(false)}
                                          className="block text-[11px] font-bold uppercase tracking-wider text-zinc-500 hover:text-zinc-950 py-1.5"
                                        >
                                          {subCat.title || subCat.name}
                                        </Link>
                                      )}
                                    </div>
                                  );
                                })}
                              </div>
                            )}
                          </>
                        ) : (
                          <Link
                            href={cat.url || `/category/${cat.slug}`}
                            onClick={() => setIsMenuOpen(false)}
                            className="block text-[12px] font-medium text-zinc-700 hover:text-zinc-950 py-3 transition-colors"
                          >
                            {cat.title || cat.name}
                          </Link>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}

              {/* Account */}
              <Link
                href="/account"
                onClick={() => setIsMenuOpen(false)}
                className="flex items-center gap-2 text-[11px] font-black tracking-widest uppercase text-zinc-800 hover:text-zinc-950 py-3 border-b border-zinc-100"
              >
                <User className="w-4 h-4" />
                My Account
              </Link>


              {/* Help (Mobile) */}
              <div className="pt-2 border-b border-zinc-100 pb-3">
                <span className="block text-[11px] font-black tracking-widest uppercase text-zinc-800 py-3">
                  Help
                </span>
                <div className="space-y-2.5 pl-1">
                  {HELP_LINKS.map((item) => (
                    <Link
                      key={item.href}
                      href={item.href}
                      onClick={() => setIsMenuOpen(false)}
                      className="block text-[12px] text-zinc-500 hover:text-zinc-950 transition-colors"
                    >
                      {item.label}
                    </Link>
                  ))}
                </div>
              </div>

              {/* Currency Selector (Mobile) */}
              <div className="pt-2">
                <button
                  onClick={() => {
                    setIsMenuOpen(false); // Close drawer to show modal
                    openCurrencyModal();
                  }}
                  className="w-full flex items-center justify-between text-[11px] font-bold tracking-widest uppercase text-zinc-800 hover:text-zinc-950 py-3 transition-colors cursor-pointer"
                >
                  <span className="flex items-center gap-2">
                    {selectedCountryCode && (
                      <img
                        src={`https://flagcdn.com/w40/${selectedCountryCode.toLowerCase()}.png`}
                        alt=""
                        className="w-4.5 h-3 object-cover rounded-xs shrink-0 border border-zinc-200/50"
                      />
                    )}
                    <span>Currency ({selectedCurrency?.symbol} {selectedCurrency?.code})</span>
                  </span>
                  <ChevronDown className="w-4 h-4 text-zinc-400" />
                </button>
              </div>
            </nav>

            {/* Footer */}
            <div className="border-t border-zinc-100 px-6 py-5 shrink-0">
              <span className="text-[10px] text-zinc-400 font-bold uppercase tracking-widest block mb-2">Need help?</span>
              <a href={`mailto:${settings["contact_email"] || "support@store.local"}`} className="text-xs text-zinc-600 hover:text-zinc-950 transition-colors">
                {settings["contact_email"] || "support@store.local"}
              </a>
            </div>
          </div>
        </div>
      )}

      {/* 3. SLOW MOTION CURRENCY SELECTOR MODAL */}
      {isCurrencyModalOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 overflow-y-auto">
          {/* Backdrop Overlay */}
          <div
            className={`fixed inset-0 bg-black/60 backdrop-blur-xs transition-opacity duration-500 ease-out ${
              isModalAnimating ? "opacity-100" : "opacity-0"
            }`}
            onClick={closeCurrencyModal}
          />

          {/* Modal Box */}
          <div
            className={`bg-white w-full max-w-[420px] rounded-[24px] border border-zinc-100 p-6 md:p-8 shadow-2xl relative z-10 transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] overflow-hidden ${
              isModalAnimating
                ? "opacity-100 scale-100 translate-y-0"
                : "opacity-0 scale-95 translate-y-8"
            }`}
          >
            {/* Modal Header */}
            <div className="flex items-center justify-between border-b border-zinc-100 pb-4 mb-4 text-left">
              <span className="text-[11px] font-bold text-zinc-500 uppercase tracking-widest flex items-center gap-2">
                {selectedCountryCode && (
                  <img
                    src={`https://flagcdn.com/w40/${selectedCountryCode.toLowerCase()}.png`}
                    alt=""
                    className="w-4.5 h-3 object-cover rounded-xs shrink-0 border border-zinc-200/50"
                  />
                )}
                <span>{selectedCountry} ({selectedCurrency?.symbol} {selectedCurrency?.code})</span>
              </span>
              <button
                onClick={closeCurrencyModal}
                className="p-1.5 text-zinc-400 hover:text-zinc-950 hover:bg-zinc-100 rounded-xl transition cursor-pointer"
                aria-label="Close modal"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Modal Content */}
            <div className="text-left">
              <h3 className="text-sm font-black uppercase tracking-wider text-zinc-950 mb-1">
                Select your shipping location.
              </h3>
              <p className="text-[9px] sm:text-[10px] font-bold text-zinc-400 uppercase tracking-widest leading-relaxed mb-5">
                YOUR CURRENT SELECTED LOCATION IS {selectedCountry?.toUpperCase()} AND YOUR ORDER WILL BE BILLED IN {selectedCurrency?.code}
              </p>

              {/* Country Search Bar */}
              <div className="relative mb-5">
                <Search className="w-4 h-4 text-zinc-400 absolute left-4 top-1/2 -translate-y-1/2" />
                <input
                  type="text"
                  placeholder="Search for a delivery location"
                  value={countrySearchQuery}
                  onChange={(e) => setCountrySearchQuery(e.target.value)}
                  className="w-full bg-zinc-100 hover:bg-zinc-200/50 focus:bg-white text-zinc-900 placeholder-zinc-400 font-bold text-xs rounded-xl pl-11 pr-4 py-3 border border-transparent focus:border-zinc-200 focus:outline-none transition-all"
                />
              </div>

              {/* Scrollable List */}
              <div className="max-h-[320px] overflow-y-auto pr-1 scrollbar-thin space-y-2">
                {countrySearchQuery.trim() === "" ? (
                  // Continent Accordions
                  CONTINENTS.map((group) => {
                    const isOpen = !!expandedContinents[group.name];
                    return (
                      <div key={group.name} className="border-b border-zinc-100 pb-2 last:border-0 last:pb-0">
                        {/* Continent Header Toggle */}
                        <button
                          onClick={() => toggleContinent(group.name)}
                          className="w-full flex items-center justify-between py-3 text-left cursor-pointer group"
                        >
                          <span className="text-[10px] font-black uppercase tracking-widest text-zinc-800 group-hover:text-zinc-950 transition-colors">
                            {group.name}
                          </span>
                          {isOpen ? (
                            <ChevronUp className="w-3.5 h-3.5 text-zinc-400 group-hover:text-zinc-600 transition-colors" />
                          ) : (
                            <ChevronDown className="w-3.5 h-3.5 text-zinc-400 group-hover:text-zinc-600 transition-colors" />
                          )}
                        </button>

                        {/* Countries List */}
                        {isOpen && (
                          <div className="pl-2 pr-1 py-1 space-y-1.5 animate-in fade-in duration-250">
                            {group.countries.map((country) => {
                              const isSelected = selectedCountry === country.name;
                              return (
                                <button
                                  key={country.name}
                                  onClick={() => handleCountrySelect(country.name, country.currency)}
                                  className={`w-full text-left py-2 px-3 text-xs font-bold rounded-xl transition-all flex justify-between items-center cursor-pointer ${
                                    isSelected
                                      ? "bg-zinc-950 text-white"
                                      : "bg-transparent text-zinc-500 hover:text-zinc-950 hover:bg-zinc-50"
                                  }`}
                                >
                                  <span className="flex items-center gap-2">
                                    <img
                                      src={`https://flagcdn.com/w20/${country.code.toLowerCase()}.png`}
                                      alt=""
                                      className="w-4 h-3 object-cover rounded-xs shrink-0 border border-zinc-100"
                                    />
                                    <span>{country.name}</span>
                                  </span>
                                  <span className="text-[10px] font-mono opacity-80">
                                    ({country.currency})
                                  </span>
                                </button>
                              );
                            })}
                          </div>
                        )}
                      </div>
                    );
                  })
                ) : (
                  // Search Results
                  <div className="space-y-1.5">
                    {searchResults.length === 0 ? (
                      <div className="text-center py-6 text-xs font-bold text-zinc-400 uppercase tracking-wider">
                        No locations found
                      </div>
                    ) : (
                      searchResults.map((country) => {
                        const isSelected = selectedCountry === country.name;
                        return (
                          <button
                            key={country.name}
                            onClick={() => handleCountrySelect(country.name, country.currency)}
                            className={`w-full text-left py-2 px-3 text-xs font-bold rounded-xl transition-all flex justify-between items-center cursor-pointer ${
                              isSelected
                                ? "bg-zinc-950 text-white"
                                : "bg-transparent text-zinc-500 hover:text-zinc-950 hover:bg-zinc-50"
                            }`}
                          >
                            <span className="flex items-center gap-2">
                              <img
                                src={`https://flagcdn.com/w20/${country.code.toLowerCase()}.png`}
                                alt=""
                                className="w-4 h-3 object-cover rounded-xs shrink-0 border border-zinc-100"
                              />
                              <span>{country.name}</span>
                            </span>
                            <span className="text-[10px] font-mono opacity-80">
                              ({country.currency})
                            </span>
                          </button>
                        );
                      })
                    )}
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
