// ─── Order date/time localisation ────────────────────────────────────────────
// The order-confirmation email and both invoice views used to render
// "when this order was placed" in whatever timezone happened to be rendering
// it — the visitor's browser for a customer-facing page, the server's clock
// for the email — so the same order showed a different hour depending on who
// was looking at it, with no indication either way of which zone it was.
//
// This resolves one fixed zone per order, from the shipping destination
// already stored on it (`Order.shippingCountry` / `shippingState`, see
// lib/orderCreation.ts), so "when was this placed" reads the same everywhere
// and is labelled with its own zone abbreviation instead of being ambiguous.
//
// One representative zone per country is a deliberate simplification for
// countries spanning several (Russia, Brazil, Indonesia, Australia, etc.) —
// a receipt doesn't need to be more precise than "the customer's country."
// The exception is the US and Canada, which get state/province-level zones:
// `lib/regions.ts` already collects a state/province code for both, this
// store's orders skew heavily US/Canada, and those two are exactly the
// countries where "just use the country" gets the hour visibly wrong.

export const TIMEZONE_BY_COUNTRY: Record<string, string> = {
  US: "America/New_York",
  CA: "America/Toronto",
  GB: "Europe/London",
  AU: "Australia/Sydney",
  DE: "Europe/Berlin",
  FR: "Europe/Paris",
  BD: "Asia/Dhaka",
  IN: "Asia/Kolkata",
  AF: "Asia/Kabul",
  AX: "Europe/Helsinki",
  AL: "Europe/Tirane",
  DZ: "Africa/Algiers",
  AS: "Pacific/Pago_Pago",
  AD: "Europe/Andorra",
  AO: "Africa/Luanda",
  AI: "America/Anguilla",
  AQ: "UTC",
  AG: "America/Antigua",
  AR: "America/Argentina/Buenos_Aires",
  AM: "Asia/Yerevan",
  AW: "America/Aruba",
  AT: "Europe/Vienna",
  AZ: "Asia/Baku",
  BS: "America/Nassau",
  BH: "Asia/Bahrain",
  BB: "America/Barbados",
  BY: "Europe/Minsk",
  BE: "Europe/Brussels",
  BZ: "America/Belize",
  BJ: "Africa/Porto-Novo",
  BM: "Atlantic/Bermuda",
  BT: "Asia/Thimphu",
  BO: "America/La_Paz",
  BA: "Europe/Sarajevo",
  BW: "Africa/Gaborone",
  BR: "America/Sao_Paulo",
  IO: "Indian/Chagos",
  BN: "Asia/Brunei",
  BG: "Europe/Sofia",
  BF: "Africa/Ouagadougou",
  BI: "Africa/Bujumbura",
  KH: "Asia/Phnom_Penh",
  CM: "Africa/Douala",
  CV: "Atlantic/Cape_Verde",
  KY: "America/Cayman",
  CF: "Africa/Bangui",
  TD: "Africa/Ndjamena",
  CL: "America/Santiago",
  CN: "Asia/Shanghai",
  CO: "America/Bogota",
  KM: "Indian/Comoro",
  CG: "Africa/Brazzaville",
  CD: "Africa/Kinshasa",
  CK: "Pacific/Rarotonga",
  CR: "America/Costa_Rica",
  CI: "Africa/Abidjan",
  HR: "Europe/Zagreb",
  CU: "America/Havana",
  CY: "Asia/Nicosia",
  CZ: "Europe/Prague",
  DK: "Europe/Copenhagen",
  DJ: "Africa/Djibouti",
  DM: "America/Dominica",
  DO: "America/Santo_Domingo",
  EC: "America/Guayaquil",
  EG: "Africa/Cairo",
  SV: "America/El_Salvador",
  GQ: "Africa/Malabo",
  ER: "Africa/Asmara",
  EE: "Europe/Tallinn",
  ET: "Africa/Addis_Ababa",
  FJ: "Pacific/Fiji",
  FI: "Europe/Helsinki",
  GF: "America/Cayenne",
  PF: "Pacific/Tahiti",
  GA: "Africa/Libreville",
  GM: "Africa/Banjul",
  GE: "Asia/Tbilisi",
  GH: "Africa/Accra",
  GI: "Europe/Gibraltar",
  GR: "Europe/Athens",
  GL: "America/Nuuk",
  GD: "America/Grenada",
  GP: "America/Guadeloupe",
  GU: "Pacific/Guam",
  GT: "America/Guatemala",
  GN: "Africa/Conakry",
  GW: "Africa/Bissau",
  GY: "America/Guyana",
  HT: "America/Port-au-Prince",
  HN: "America/Tegucigalpa",
  HK: "Asia/Hong_Kong",
  HU: "Europe/Budapest",
  IS: "Atlantic/Reykjavik",
  ID: "Asia/Jakarta",
  IR: "Asia/Tehran",
  IQ: "Asia/Baghdad",
  IE: "Europe/Dublin",
  IL: "Asia/Jerusalem",
  IT: "Europe/Rome",
  JM: "America/Jamaica",
  JP: "Asia/Tokyo",
  JO: "Asia/Amman",
  KZ: "Asia/Almaty",
  KE: "Africa/Nairobi",
  KI: "Pacific/Tarawa",
  KW: "Asia/Kuwait",
  KG: "Asia/Bishkek",
  LA: "Asia/Vientiane",
  LV: "Europe/Riga",
  LB: "Asia/Beirut",
  LS: "Africa/Maseru",
  LR: "Africa/Monrovia",
  LY: "Africa/Tripoli",
  LI: "Europe/Vaduz",
  LT: "Europe/Vilnius",
  LU: "Europe/Luxembourg",
  MO: "Asia/Macau",
  MK: "Europe/Skopje",
  MG: "Indian/Antananarivo",
  MW: "Africa/Blantyre",
  MY: "Asia/Kuala_Lumpur",
  MV: "Indian/Maldives",
  ML: "Africa/Bamako",
  MT: "Europe/Malta",
  MH: "Pacific/Majuro",
  MR: "Africa/Nouakchott",
  MU: "Indian/Mauritius",
  MX: "America/Mexico_City",
  FM: "Pacific/Pohnpei",
  MD: "Europe/Chisinau",
  MC: "Europe/Monaco",
  MN: "Asia/Ulaanbaatar",
  ME: "Europe/Podgorica",
  MA: "Africa/Casablanca",
  MZ: "Africa/Maputo",
  MM: "Asia/Yangon",
  NA: "Africa/Windhoek",
  NP: "Asia/Kathmandu",
  NL: "Europe/Amsterdam",
  NC: "Pacific/Noumea",
  NZ: "Pacific/Auckland",
  NI: "America/Managua",
  NE: "Africa/Niamey",
  NG: "Africa/Lagos",
  NO: "Europe/Oslo",
  OM: "Asia/Muscat",
  PK: "Asia/Karachi",
  PS: "Asia/Gaza",
  PA: "America/Panama",
  PG: "Pacific/Port_Moresby",
  PY: "America/Asuncion",
  PE: "America/Lima",
  PH: "Asia/Manila",
  PL: "Europe/Warsaw",
  PT: "Europe/Lisbon",
  QA: "Asia/Qatar",
  RO: "Europe/Bucharest",
  RU: "Europe/Moscow",
  RW: "Africa/Kigali",
  SA: "Asia/Riyadh",
  SN: "Africa/Dakar",
  RS: "Europe/Belgrade",
  SG: "Asia/Singapore",
  SK: "Europe/Bratislava",
  SI: "Europe/Ljubljana",
  ZA: "Africa/Johannesburg",
  ES: "Europe/Madrid",
  LK: "Asia/Colombo",
  SE: "Europe/Stockholm",
  CH: "Europe/Zurich",
  TW: "Asia/Taipei",
  TH: "Asia/Bangkok",
  TN: "Africa/Tunis",
  TR: "Europe/Istanbul",
  UA: "Europe/Kyiv",
  AE: "Asia/Dubai",
  UY: "America/Montevideo",
  UZ: "Asia/Tashkent",
  VE: "America/Caracas",
  VN: "Asia/Ho_Chi_Minh",
  ZM: "Africa/Lusaka",
  ZW: "Africa/Harare",
}

/** IANA zone per US state/territory code, matching `lib/regions.ts`'s `US_STATES`. */
export const TIMEZONE_BY_US_STATE: Record<string, string> = {
  AL: "America/Chicago",
  AK: "America/Anchorage",
  AZ: "America/Phoenix",
  AR: "America/Chicago",
  CA: "America/Los_Angeles",
  CO: "America/Denver",
  CT: "America/New_York",
  DE: "America/New_York",
  DC: "America/New_York",
  FL: "America/New_York",
  GA: "America/New_York",
  HI: "Pacific/Honolulu",
  ID: "America/Denver",
  IL: "America/Chicago",
  IN: "America/Indiana/Indianapolis",
  IA: "America/Chicago",
  KS: "America/Chicago",
  KY: "America/New_York",
  LA: "America/Chicago",
  ME: "America/New_York",
  MD: "America/New_York",
  MA: "America/New_York",
  MI: "America/Detroit",
  MN: "America/Chicago",
  MS: "America/Chicago",
  MO: "America/Chicago",
  MT: "America/Denver",
  NE: "America/Chicago",
  NV: "America/Los_Angeles",
  NH: "America/New_York",
  NJ: "America/New_York",
  NM: "America/Denver",
  NY: "America/New_York",
  NC: "America/New_York",
  ND: "America/Chicago",
  OH: "America/New_York",
  OK: "America/Chicago",
  OR: "America/Los_Angeles",
  PA: "America/New_York",
  RI: "America/New_York",
  SC: "America/New_York",
  SD: "America/Chicago",
  TN: "America/Chicago",
  TX: "America/Chicago",
  UT: "America/Denver",
  VT: "America/New_York",
  VA: "America/New_York",
  WA: "America/Los_Angeles",
  WV: "America/New_York",
  WI: "America/Chicago",
  WY: "America/Denver",
}

/** IANA zone per Canadian province/territory code, matching `lib/regions.ts`'s `CA_PROVINCES`. */
export const TIMEZONE_BY_CA_PROVINCE: Record<string, string> = {
  AB: "America/Edmonton",
  BC: "America/Vancouver",
  MB: "America/Winnipeg",
  NB: "America/Moncton",
  NL: "America/St_Johns",
  NS: "America/Halifax",
  NT: "America/Yellowknife",
  NU: "America/Iqaluit",
  ON: "America/Toronto",
  PE: "America/Halifax",
  QC: "America/Toronto",
  SK: "America/Regina",
  YT: "America/Whitehorse",
}

/** The zone a given shipping destination's local time should be read in. */
export function resolveOrderTimezone(
  countryCode?: string | null,
  stateCode?: string | null
): string {
  const country = (countryCode || "").toUpperCase()
  const state = (stateCode || "").toUpperCase()

  if (country === "US" && TIMEZONE_BY_US_STATE[state]) return TIMEZONE_BY_US_STATE[state]
  if (country === "CA" && TIMEZONE_BY_CA_PROVINCE[state]) return TIMEZONE_BY_CA_PROVINCE[state]
  return TIMEZONE_BY_COUNTRY[country] || "UTC"
}

/**
 * An order's placed-at date and time, in the customer's own timezone, with
 * the zone abbreviation appended (e.g. "Sep 23, 2026, 7:14 PM EDT") so it's
 * unambiguous which "local" time is being shown.
 */
export function formatOrderDateTime(
  date: Date | string,
  countryCode?: string | null,
  stateCode?: string | null
): string {
  const d = typeof date === "string" ? new Date(date) : date
  const timeZone = resolveOrderTimezone(countryCode, stateCode)
  return new Intl.DateTimeFormat("en-US", {
    timeZone,
    dateStyle: "medium",
    timeStyle: "short",
    timeZoneName: "short",
  }).format(d)
}
